export const CREATE_GALLERY = "CREATE_GALLERY";
export const LOAD_GALLERY_SUCCESS = "LOAD_GALLERY_SUCCESS";
export const LOAD_VENDERS_SUCCESS = "LOAD_VENDERS_SUCCESS";
export const CREATE_GALLERY_SUCCESS = "CREATE_GALLERY_SUCCESS";
export const UPDATE_GALLERY_SUCCESS = "UPDATE_GALLERY_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";
