export const CREATE_GALLERY = "CREATE_GALLERY";
export const LOAD_GALLERY_SUCCESS = "LOAD_GALLERY_SUCCESS";
export const LOAD_VENDERS_SUCCESS = "LOAD_VENDERS_SUCCESS";
export const CREATE_GALLERY_SUCCESS = "CREATE_GALLERY_SUCCESS";
export const UPDATE_GALLERY_SUCCESS = "UPDATE_GALLERY_SUCCESS";
